### ISSUE TITLE
Not able to download the datasets

### ISSUE THREAD

**Issue by rsuwaileh** [uhuohuy/GazPNE#3]
Hello,

According to step #3, we can download the data to test the pre-trained model:

> The three [annotated tweet data](https://rebrand.ly/LocationsDataset) sets should be put under the data folder.

However, the provided link is broken. Can you please provide a working link or at least describe the format of the data?

Thanks in advance,
Reem

**Comment by xukehu** [comment]
Dear Reem,
Thanks for your interests. I just tested the link and found it still works. I use the three datasets from the LNEx project (https://github.com/halolimat/LNEx). You can find more information there.
Thanks,
Xuke
