### ISSUE TITLE
Environment configurations

### ISSUE THREAD

**Issue by rsuwaileh** [uhuohuy/GazPNE#4]
Hello,

Could you please provide the list of all libraries and their versions used to run the model?
In case it's possible, providing an exported .yml file of the environment used to run the experiments would be great. 

This is some errors that I'm getting when running `model_test.py`:

```
Traceback (most recent call last):
  File "model_test.py", line 9, in <module>
    from Gazetteer_weight import load_embeding
  File "/home/local/.../Gazetteer_weight.py", line 19, in <module>
    from BertEmbeds import BertEmbeds
```

```
Traceback (most recent call last):
  File "model_test.py", line 13, in <module>
    from utility import *
  File "/home/local/QCRI/rsuwaileh/workspace/LMP/GazPNE/utility.py", line 3, in <module>
    from constant import POS_TAGS
ImportError: cannot import name 'POS_TAGS'
```

Thanks in advance,
Reem

**Comment by xukehu** [comment]
Dear Reem,
Thanks for pointing out the error. I will update the code soon. By the way, we have dramatically improved GazPNE by proposing GazPNE2 (https://github.com/uhuohuy/GazPNE2). We are still preparing the code of GazPNE2 but will finish it soon.
Thanks,
Xuke

**Comment by rsuwaileh** [comment]
Hey Xuke,

Thanks a lot for the quick response!
I noticed that GazPNE_v2 is not a published work yet, hence I have to continue using v1.

I also didn't find in the repo of GazPNE_v2 what resolves the errors reported above.
Looking forward to your updates.

Thanks,
Reem

**Comment by xukehu** [comment]
Hi Rsuwaileh,
I have rerun the code and solved all the issues. I have also prepared the requirements.txt, from which you can install the dependencies. It should work now.
If you meet any further issues, feel free to let me know.
Best,
Xuke
